# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: casaos-cli
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -v ./...
builds:
  - id: casaos-cli-amd64
    binary: build/sysroot/usr/bin/casaos-cli
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: casaos-cli-arm64
    binary: build/sysroot/usr/bin/casaos-cli
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: casaos-cli-arm-7
    binary: build/sysroot/usr/bin/casaos-cli
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
archives:
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-v{{ .Version }}"
    id: casaos-cli
    builds:
      - casaos-cli-amd64
      - casaos-cli-arm64
      - casaos-cli-arm-7
    replacements:
      arm: arm-7
    files:
      - build/**/*
  - name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}"
    id: casaos-cli-migration-tool
    builds:
      - casaos-cli-migration-tool-amd64
      - casaos-cli-migration-tool-arm64
      - casaos-cli-migration-tool-arm-7
    replacements:
      arm: arm-7
    files:
      - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: IceWhaleTech
    name: CasaOS-CLI
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
